### ISSUE TITLE
Swagger authentication fails

### ISSUE THREAD

**Issue by preriasusi** [apinf/api-umbrella-dashboard#1441]
https://nightly2.apinf.io/api/GAEtqKnGe6JvEWJ43

Go to API Ernit Thursday 2 in nightly2. Open documentation tab.

Click autheticate. input your API key and perss authentigate. 

Documentation disappears, and the text "fetching resource list: https://nightly2.apinf.io/gridfs/DocumentationFiles/id/88762abedccd0f38b5b62759; Please wait." remains forever.

![screen shot 2016-08-25 at 11 30 09](https://cloud.githubusercontent.com/assets/7766712/17961998/5729cde8-6ab7-11e6-939d-050aaee5cc12.png)

**Comment by jykae** [comment]
@preriasusi I take a look at this tomorrow

**Comment by jykae** [comment]
@preriasusi Got header added to request, small fix.
```
securityDefinitions:
  ApinfAuthorization:
    description: Please give your Apinf API key here
    type: apiKey
    in: header
    name: api_key
```
Name is the exact header variable name, and cannot have whitespace. Now it goes through, and header goes with request.
![nayttokuva 2016-08-25 kello 16 27 45](https://cloud.githubusercontent.com/assets/293452/17970923/3577b622-6ae1-11e6-8d48-86ded20a234f.png)
