### ISSUE TITLE
Parse API configurations

### ISSUE THREAD

**Issue by bajiat** [apinf/api-umbrella-dashboard#215]
Related to #72. When API configuration is uploaded, it needs to be parsed and inserted into the relevant collections.

Useful resources
-------------------
* [API Umbrella config parser (JavaScript)](https://github.com/NREL/api-umbrella-config)

Definition of done
---
* [x] Describe structure of API Umbrella configuration files.
* [x] Determine how to insert API configurations into Apinf collections.
* [x] Implement handle to parse
* [x] Insert API configuration data.

**Comment by bajiat** [comment]
@frenchbread, will you please consider taking this task?

**Comment by frenchbread** [comment]
yep

**Comment by bajiat** [comment]
@frenchbread Can you also give the size estimate, e.g. how many hours it will take?

**Comment by frenchbread** [comment]
@bajiat I have a question regarding definition of done list, if we could talk about it on a stand up, I will provide time estimation more exact.

**Comment by frenchbread** [comment]
The basic api config file looks like this:
```yaml
---
apis:
- _id: 35d0e433-91e8-4c1d-8c31-97afcfe7de7e
  backend_host: maps.googleapis.com
  backend_protocol: http
  balance_algorithm: least_conn
  created_at: 2014-11-12 15:42:27.461000000 Z
  created_by: bf9c6314-8946-4204-b106-79d33160fb94
  frontend_host: apinf.com
  name: Google Maps
  servers:
  - _id: 17f52375-4984-4348-9588-bee123404f12
    host: maps.googleapis.com
    port: 80
  settings:
    _id: 6c58a7a4-3e89-46c7-b604-748e88b7a3c7
    disable_api_key: 
    error_data: {}
    error_templates: {}
    rate_limit_mode: 
    require_https: 
  sort_order: 1
  updated_at: 2014-11-13 07:37:58.264000000 Z
  updated_by: bf9c6314-8946-4204-b106-79d12370fb94
  url_matches:
  - _id: 7240c758-d380-436b-b612-730d3237ddc0
    backend_prefix: "/"
    frontend_prefix: "/google/"
  version: 2
```

There can be s number of apis in one api config file.
